'use client';

import { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Loader2 } from 'lucide-react';

interface CreatePRDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSubmit: (data: {
    branchName: string;
    prTitle: string;
    prBody: string;
    token: string;
  }) => void;
  loading?: boolean;
  defaultToken?: string;
}

export function CreatePRDialog({
  open,
  onOpenChange,
  onSubmit,
  loading = false,
  defaultToken = '',
}: CreatePRDialogProps) {
  const timestamp = Date.now();
  const [branchName, setBranchName] = useState(`readmelingo-translations-${timestamp}`);
  const [prTitle, setPrTitle] = useState('Add multilingual documentation (powered by ReadMeLingo)');
  const [prBody, setPrBody] = useState(
    'This PR adds multilingual documentation generated by ReadMeLingo.\n\nGenerated with ❤️ by ReadMeLingo'
  );
  const [token, setToken] = useState(defaultToken);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!token.trim()) {
      return;
    }

    onSubmit({
      branchName: branchName.trim(),
      prTitle: prTitle.trim(),
      prBody: prBody.trim(),
      token: token.trim(),
    });
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[600px]">
        <form onSubmit={handleSubmit}>
          <DialogHeader>
            <DialogTitle>Create Pull Request</DialogTitle>
            <DialogDescription>
              Create a pull request with the translated documentation files.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="branch-name">Branch Name</Label>
              <Input
                id="branch-name"
                value={branchName}
                onChange={(e) => setBranchName(e.target.value)}
                disabled={loading}
                required
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="pr-title">PR Title</Label>
              <Input
                id="pr-title"
                value={prTitle}
                onChange={(e) => setPrTitle(e.target.value)}
                disabled={loading}
                required
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="pr-body">PR Description</Label>
              <Textarea
                id="pr-body"
                value={prBody}
                onChange={(e) => setPrBody(e.target.value)}
                disabled={loading}
                rows={6}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="pr-token">GitHub Token</Label>
              <Input
                id="pr-token"
                type="password"
                placeholder="ghp_xxxxxxxxxxxx"
                value={token}
                onChange={(e) => setToken(e.target.value)}
                disabled={loading}
                required
              />
              <p className="text-sm text-muted-foreground">
                Required to create the pull request
              </p>
            </div>
          </div>

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              disabled={loading}
            >
              Cancel
            </Button>
            <Button type="submit" disabled={loading || !token.trim()}>
              {loading ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Creating...
                </>
              ) : (
                'Create Pull Request'
              )}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

