import { NextRequest, NextResponse } from 'next/server';
import {
  getDefaultBranch,
  getLatestCommitSha,
  createBranch,
  createOrUpdateFile,
  createPullRequest,
} from '@/lib/github';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const {
      owner,
      repo,
      translatedFiles,
      branchName,
      prTitle,
      prBody,
      token,
    } = body;

    if (!owner || !repo) {
      return NextResponse.json(
        { error: 'Owner and repo are required' },
        { status: 400 }
      );
    }

    if (!translatedFiles || !Array.isArray(translatedFiles) || translatedFiles.length === 0) {
      return NextResponse.json(
        { error: 'Translated files array is required' },
        { status: 400 }
      );
    }

    if (!token) {
      return NextResponse.json(
        { error: 'GitHub token is required for PR creation' },
        { status: 400 }
      );
    }

    const defaultBranch = await getDefaultBranch(owner, repo, token);
    const baseSha = await getLatestCommitSha(owner, repo, defaultBranch, token);

    const finalBranchName = branchName || `readmelingo-translations-${Date.now()}`;

    await createBranch(owner, repo, finalBranchName, baseSha, token);

    for (const file of translatedFiles) {
      await createOrUpdateFile(
        owner,
        repo,
        file.path,
        file.content,
        finalBranchName,
        token,
        `Add ${file.locale} translation for ${file.path}`
      );
    }

    const finalPrTitle = prTitle || 'Add multilingual documentation (powered by ReadMeLingo)';
    const finalPrBody = prBody || `
This PR adds multilingual documentation generated by [ReadMeLingo](https://readmelingo.dev).

## Languages Added
${translatedFiles.map((f: { locale: string }) => `- ${f.locale}`).filter((v: string, i: number, a: string[]) => a.indexOf(v) === i).join('\n')}

## Files Translated
${translatedFiles.map((f: { path: string }) => `- ${f.path}`).join('\n')}

---
Generated with ❤️ by ReadMeLingo
    `.trim();

    const prUrl = await createPullRequest(
      owner,
      repo,
      finalPrTitle,
      finalPrBody,
      finalBranchName,
      defaultBranch,
      token
    );

    return NextResponse.json({
      success: true,
      prUrl,
      branch: finalBranchName,
    });
  } catch (error) {
    console.error('Error creating pull request:', error);
    
    return NextResponse.json(
      { 
        error: error instanceof Error ? error.message : 'Failed to create pull request',
      },
      { status: 500 }
    );
  }
}

